version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    #volumes:
    #  - my-db:/var/lib/mysql

#volumes:
  #my-db:
